### ISSUE TITLE
关于supernet scheduler

### ISSUE THREAD

**Issue by nbl97** [microsoft/AutoML#21]
lib/utils/util.py 中，scheduler 的自定义函数为 lambda step: (cfg.LR - step / ITERS)，是否该改为  lambda step: (1 - step / ITERS) ？

**Comment by Z7zuqer** [comment]
Hi,

This scheduler is designed to help train a better supernet. In the beginning, due to random architectures, we need large learning rate to train this network. As the training process goes on, we should reduce learning rate at a steady pace. You could directly change the learning rate to 1 or use another learning rate.

Best,
Hao.
