### ISSUE TITLE
FLOPs in the paper 

### ISSUE THREAD

**Issue by GG-Bonds** [microsoft/AutoML#35]
hi, I have a question about the **FLOPs** reported in the paper. In Table 5, **Cream-S got 287M FLOPs**. But, I found it should be **318M FLOPs** based on the architecture in the appendix.

**Comment by Z7zuqer** [comment]
Hi

Thanks for your interest in our project!

We calculate Flops of the model by thop, which is the most widely used counting flops library.  

Could you share more details of your way of counting flops that we could check what happened?

Best,

Hao.

**Comment by GG-Bonds** [comment]
Thanks for your reply.&nbsp;


Please see the following list.&nbsp;


According to issue #31, DS is same to MB. So, we directly used "MB 4 3x3 SE" to replace "DS 4 3x3 SE".
[Stem [5419008],&nbsp;
MB 4 3x3 SE [32917504], (According to issue #31, DS is same to MB)
MB 6 5x5 SE [34023936],&nbsp;
MB 6 5x5 SE [18186624],&nbsp;
MB 6 5x5 SE [19785600],&nbsp;
MB 6 5x5 SE [12494400],&nbsp;
MB 6 5x5 SE [16014720],&nbsp;
MB 6 3x3 SE [17520000],&nbsp;
MB 6 5x5 SE [19025280],&nbsp;
MB 6 5x5 SE [24664320],&nbsp;
MB 6 5x5 SE [24664320],&nbsp;
MB 6 5x5 SE [24664320],&nbsp;
MB 6 5x5 SE [17128512],&nbsp;
MB 6 5x5 SE [23750784],&nbsp;
MB 6 5x5 SE [23750784],&nbsp;
Conv 1x1 [3010560],&nbsp;
GAP [0],&nbsp;
Conv 1x1 [409600],&nbsp;
FC [1280000]]


The final FLOPs of the overall layers in the above list is 318M.&nbsp;


I have double checked with my colleagues about the FLOPs and confirmed the result is right.


### When we used the *actual* deep-wise conv (one DW conv with one 1x1 conv) implemented in timm, the FLOPs is 287M.###





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/AutoML"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/AutoML] FLOPs in the paper  (#35)





 
Hi
 
Thanks for your interest in our project!
 
We calculate Flops of the model by thop, which is the most widely used counting flops library.
 
Could you share more details of your way of counting flops that we could check what happened?
 
Best,
 
Hao.

**Comment by Z7zuqer** [comment]
Hi,

According to the supplementary materials of our paper, the structure of our network is in Tab.8, as demonstrated in the following:

Conv,
DSConv(Here, DSconv is not MB, instead, it's only DS conv, which is implemented in [timm](https://github.com/rwightman/pytorch-image-models/blob/ef1e2e12be9ef9e04ead617685eebd0cb070289e/timm/models/efficientnet_blocks.py#L82))
MBconv(pw+dw+pw)
MBconv(pw+dw+pw)
MBconv(pw+dw+pw)
MBconv(pw+dw+pw)
MBconv(pw+dw+pw)
Conv
GAP
Conv
FC

And, according to the widely used counting flops library thop, the flops of the network is 287M. In Issue [#31](https://github.com/microsoft/AutoML/issues/31), I mean an MBconv is composed of *one* pointwise conv, *one* depthwise conv and *one* pointwise conv. You could also refer to [this line](https://github.com/microsoft/AutoML/blob/d895e22107fe4785511e93df622670547509dfbc/Cream/lib/models/structures/supernet.py#L165) that define the first DSconv.

Best,

Hao.

**Comment by GG-Bonds** [comment]
Thanks for your reply.

According to your reply, DW is dw+pw. But, how to explain the expand rate of "DS 4 3x3 SE" is set as 4? How can DW have the expand rate 4? 

And as you said in issue #31 that " 'DS' and 'MB' are the same thing", what does the word "same" mean? Same numbers of conv layers and/or some other things?

I only would like to know the true way of your implementation for following your work. 

Thanks.

**Comment by Z7zuqer** [comment]
Hi,

1) Our 'MB' is the same as 'IR' in TIMM. You could refer to this [implementation](https://github.com/rwightman/pytorch-image-models/blob/ef1e2e12be9ef9e04ead617685eebd0cb070289e/timm/models/efficientnet_blocks.py#L135) for more details.

2) For the definition of DS, we deal with it as listed in the following: a) we define the DS by the string as defined in [here](https://github.com/microsoft/AutoML/blob/d895e22107fe4785511e93df622670547509dfbc/Cream/lib/models/structures/supernet.py#L165) b) Then, we follow TIMM implementation to deal with this string to get the required information, and send it to [here](https://github.com/microsoft/AutoML/blob/d895e22107fe4785511e93df622670547509dfbc/Cream/lib/models/builders/build_supernet.py#L101) c) Since we import TIMM library [here](https://github.com/microsoft/AutoML/blob/d895e22107fe4785511e93df622670547509dfbc/Cream/lib/models/builders/build_supernet.py#L6), we construct the DS block using the [TIMM implementation](https://github.com/rwightman/pytorch-image-models/blob/ef1e2e12be9ef9e04ead617685eebd0cb070289e/timm/models/efficientnet_blocks.py#L82). And TIMM implementation doesn't use expansion rate, so 'DS 4 3x3 SE' is 'DS 3x3 SE'. The expansion rate is useless in the definition of the DS block.

3) For issue #31, the hyperparameters of an MBconv consist of a) kernel size b) expansion rate. These two hyperparameters are mostly for the depthwise convolution in an MBconv.(expansion rate is for the channel of DW, though it is used in PW.) So, they are the same thing if we only consider the searchable hyperparameter. 

Best,

Hao.

**Comment by Z7zuqer** [comment]
Hi,

We're closing this issue, if you have any questions, please feel free to re-open it.

Best,

Hao.
