### ISSUE TITLE
question about irpe

### ISSUE THREAD

**Issue by kpmokpmo** [microsoft/AutoML#45]
Hi, thanks for your work. Just a quick question.

# line194 of irpe.py:
def _rp_2d_product(diff, **kwargs):
    beta_int = int(kwargs['beta'])
    S = 2 * beta_int + 1
    # the output of piecewise index function is in [-beta_int, beta_int]
    r = piecewise_index(diff[:, :, 0], **kwargs) + beta_int  # [0, 2 * beta_int]
    c = piecewise_index(diff[:, :, 1], **kwargs) + beta_int  # [0, 2 * beta_int]
    pid = r * S + c
    return pid

r and c supposed to be piecewise index for row and column respectively. But I can't understand why times r with the buckets number(or square root of buckets number in product method)?

Thank you!

**Comment by wkcn** [comment]
Thanks for your attention to our work : )

Let `F` denote the function `piecewise_index`, `x` denote the relative offset.

The range of `F(x)` is `[-beta, beta]`, namely `F(x) \in [-beta, beta]`. `(F(x) + beta) \in [0, 2 * beta]`. 

Therefore `r, c \in [0, 2 * beta]`, and the number of integers in `[0, 2 * beta]` is `2 * beta + 1`, denoted by the constant value `S` (square root of buckets number in product method).

In order to get **a unique bucket for different pair `(r, c)`**, `(r * S + c) \in [0, S * S)` is a unique ID of the bucket for the pair `(r, c)`, where `S * S` is the number of buckets.

**Comment by kpmokpmo** [comment]
I get it. Thanks very much!

**Comment by kpmokpmo** [comment]
I get it. Thanks very much!
