### ISSUE TITLE
Problems about

### ISSUE THREAD

**Issue by DingYuan0118** [microsoft/AutoML#48]

**Comment by DingYuan0118** [comment]
In your paper:
Euclidean method is:

![公式1](https://user-images.githubusercontent.com/42141845/129504787-96b1f4d7-abe2-40f7-b1b7-0fd4b9174903.JPG)

Quantization method is:
![公式2](https://user-images.githubusercontent.com/42141845/129504818-23b907fd-11cb-4b62-906e-66883ce397c8.JPG)

But in your [code](https://github.com/microsoft/AutoML/blob/main/iRPE/DeiT-with-iRPE/irpe.py#131-172):
```
def _rp_2d_euclidean(diff, **kwargs):
    ...
    dis = diff.square().sum(2).float().sqrt().round()
    return piecewise_index(dis, **kwargs)
```

```
def _rp_2d_quant(diff, **kwargs):
    ....
    dis = diff.square().sum(2)
    return piecewise_index(dis, **kwargs)
```

**Comment by wkcn** [comment]
Thank you for pointing it out !

In Euclidean method, we first compute the relative distance `diff.square().sum(2).float().sqrt()`. Since the relative distance is a floating number, we convert it into an integer by `.round()` then pass it into the piecewise function `g(x)`. The 2D relative position (1, 0) and (1, 1) will be mapped into the index 1, because their rounded relative distances are both 1.

In Quantization method, we do not compute the square-root to allow two neighbors with different relative distances map into different indexes. The quantization is implemented by removing the operators `sqrt` and `round`. The 2D relative positions (1, 0) and (1, 1) will be mapped into the indexes 1 and 2, respectively.

Here is a simple example. We visualize the indexes (the reference point is the center).
```python
from irpe import _rp_2d_euclidean, _rp_2d_quant, get_absolute_positions
import torch
from easydict import EasyDict as edict

max_height = max_width = 7
dtype = torch.float32
device = torch.device('cpu')

pos = get_absolute_positions(max_height, max_width, dtype, device)

# compute the offset of a pair of 2D relative positions
max_L = max_height * max_width
pos1 = pos.view((max_L, 1, 2))
pos2 = pos.view((1, max_L, 2))
# diff: shape of (L, L, 2)
diff = pos1 - pos2

ratio = 30
kwargs = edict(alpha=1 * ratio, beta=2 * ratio, gamma=8 * ratio, dtype=dtype)
print("Euclidean:")
euc = _rp_2d_euclidean(diff, **kwargs)
print(euc[49//2].view(7, 7))

print("Quantization:")
quant = _rp_2d_quant(diff, **kwargs)
print(quant[49//2].view(7, 7))
```
It outputs:
```
Euclidean:
tensor([[4., 4., 3., 3., 3., 4., 4.],
        [4., 3., 2., 2., 2., 3., 4.],
        [3., 2., 1., 1., 1., 2., 3.],
        [3., 2., 1., 0., 1., 2., 3.],
        [3., 2., 1., 1., 1., 2., 3.],
        [4., 3., 2., 2., 2., 3., 4.],
        [4., 4., 3., 3., 3., 4., 4.]])
Quantization:
tensor([[18., 13., 10.,  9., 10., 13., 18.],
        [13.,  8.,  5.,  4.,  5.,  8., 13.],
        [10.,  5.,  2.,  1.,  2.,  5., 10.],
        [ 9.,  4.,  1.,  0.,  1.,  4.,  9.],
        [10.,  5.,  2.,  1.,  2.,  5., 10.],
        [13.,  8.,  5.,  4.,  5.,  8., 13.],
        [18., 13., 10.,  9., 10., 13., 18.]])
```
